project:
  type: website
  output-dir: docs
  preview:
    port: 4200
  render:
    #- "v1.qmd"
    - "working.qmd"
    - "tables.qmd"
    
    #- "*.qmd"
  # resources: 
  #     - "Manuscript/output/"
  #     - "Manuscript/Assets/"
  #     #- "Manuscript/assets/figs/"
    
# exclude: ["*.rds","*.tex","*.csl","*.bib","docs*","404.html","_old*","out.bib",
#   "*.pdf","*.R",".obsidian","Rproj","R","Bib","exp","HTW_Analysis/**","*HTW_Modelling/**","Motivated*"]


website:
  title: "GD Chapter"
  repo-url: https://github.com/tegorman13/ai_gd_chapter/
  site-url: "https://tegorman13.github.io/ai_gd_chapter/working.html"
  repo-actions: [source, edit, issue]
  reader-mode: true
  page-navigation: true

format:
  html: 
    date: today
    toc: true
    lightbox: true
    link-citations: true
    page-layout: full
    theme: 
      light: cosmo
      dark: cyborg
  gfm: 
    output-file: "gd_chapter_v3.md"
  hikmah-manuscript-docx: 
    output-file: "gd_chapter_v3_hikmah.docx"
    toc: false
  hikmah-manuscript-pdf:
    echo: false
    output-file: "gd_chapter_v3.pdf"
    mainfont: "EB Garamond"
    mainfontoptions:
        - "Numbers=Proportional"
        - "Numbers=OldStyle"
    mathfont: "Libertinus Math"
    include-in-header:
      text: |
          \newcommand*\NewPage{\newpage\null\thispagestyle{empty}\newpage}
          \usepackage{mathtools}
          \everydisplay\expandafter{\the\everydisplay\small}
          \usepackage{float}
          \floatplacement{figure}{H}
          \floatplacement{table}{H}
          \usepackage{setspace}
          \pagenumbering{arabic}
          \usepackage{titlesec}
#   pdf: 
#     documentclass: article
#     papersize: letter
#     toc: false
#     fontsize: 11pt
#     linestretch: 1.5
  docx:
    prefer-html: true
    output-file: "gd_ai_chapter_v3.docx"
    toc: false



author:
- name: Thomas E. Gorman
  affiliations: 
  - name: Communication and Cognition Lab, Purdue University, USA
    affiliation-url: https://web.ics.purdue.edu/~treimer/
  - name: College of Liberal Arts Research Academy
    affiliation-url: https://cla.purdue.edu/about/college-initiatives/research-academy/
  url: https://tegorman13.github.io/
  email: tegorman@purdue.edu
  orcid: "0000-0001-5366-5442"
- name: Torsten Reimer
  affiliation: Communication and Cognition Lab, Purdue University, USA
  affiliation-url: https://cla.purdue.edu/communication/
  url: https://web.ics.purdue.edu/~treimer/
  email: treimer@purdue.edu
  orcid: 0000-0002-7419-0076




bibliography: [Assets/ccl_bib.bib]
csl: Assets/apa.csl